stable/aws-xray/Chart.yaml, stable/aws-xray/values.yaml
=> Update aws xray version to 3.2.0

stable/asprom/Chart.yaml, stable/asprom/values.yaml
=> Bump asprom version to 1.7.0

stable/asprom/Chart.yaml, stable/asprom/README.md, stable/asprom/values.yaml
=> Bump asprom version to 1.9.0

stable/asprom/Chart.yaml, stable/asprom/README.md, stable/asprom/values.yaml
=> Bump asprom version to 1.9.1

stable/asprom/Chart.yaml, stable/asprom/README.md, stable/asprom/values.yaml
=> Bump asprom version to 1.10.0

stable/aws-xray/Chart.yaml, stable/aws-xray/templates/daemonset.yaml, stable/aws-xray/values.yaml
if image.pullSecrets is not defined, the bock was rendered with an empty value. Causing on EKS, the kubelet to keep throwing exceptions like:
I0414 02:06:57.011774       1 node_authorizer.go:191] NODE DENY: ip-XX-XX-XX-XX.xx-west-2.compute.internal &authorizer.AttributesRecord{User:(*user.DefaultInfo)(0xc01ad1fa00), Verb:"list", Namespace:"kube-system", APIGroup:"", APIVersion:"v1", Resource:"secrets", Subresource:"", Name:"", ResourceRequest:true, Path:"/api/v1/namespaces/kube-system/secrets"}
**Special …
=> Template image.pullSecrets only if defined

stable/asprom/Chart.yaml, stable/asprom/README.md, stable/asprom/values.yaml
New asprom version has been released
=> Bump asprom version to 1.10.1

stable/goldpinger/.helmignore, stable/goldpinger/Chart.yaml, stable/goldpinger/README.md, stable/goldpinger/templates/NOTES.txt, stable/goldpinger/templates/_helpers.tpl, stable/goldpinger/templates/clusterrole.yaml, stable/goldpinger/templates/clusterrolebinding.yaml, stable/goldpinger/templates/daemonset.yaml, stable/goldpinger/templates/ingress.yaml, stable/goldpinger/templates/podsecuritypolicy.yaml, stable/goldpinger/templates/service.yaml, stable/goldpinger/templates/serviceaccount.yaml, stable/goldpinger/templates/servicemonitor.yaml, stable/goldpinger/values.yaml
=> Add goldpinger helm chart

charts/goldpinger/Chart.yaml, charts/goldpinger/README.md, charts/goldpinger/templates/daemonset.yaml, charts/goldpinger/templates/ingress.yaml, charts/goldpinger/templates/service.yaml, charts/goldpinger/values.yaml
This PR gives the user the option to add additional labels to pod, ingress and service using the values file.
=> add labels to ingress, pod and service

charts/goldpinger/Chart.yaml, charts/goldpinger/README.md, charts/goldpinger/values.yaml
Upgrade image tags
* Update values.yaml
* Update Chart.yaml
* Update version in README.md
=> Update image tags for version 3.0.0

charts/aws-xray/Chart.yaml, charts/aws-xray/README.md, charts/goldpinger/Chart.yaml, charts/goldpinger/README.md
Properly README for aws-xray and goldpinger charts
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*:
fixes #28 
=> Update repo installation process in READMEs

charts/goldpinger/Chart.yaml, charts/goldpinger/README.md, charts/goldpinger/values.yaml
**What this PR does / why we need it**: 
Update tag goldpinger image
=> Update image tag

charts/goldpinger/Chart.yaml, charts/goldpinger/README.md, charts/goldpinger/values.yaml
Use latest goldpinger version as a default version
=> Bump goldpinger version to 3.2.0

charts/aws-xray/Chart.yaml, charts/aws-xray/templates/serviceaccount.yaml
Adding support for  IAM roles for Service Accounts.
=> add support for IRSA

charts/goldpinger/Chart.yaml, charts/goldpinger/templates/podsecuritypolicy.yaml
Fix typo in name of podsecuritypolicy
=> Fix typo in podsecuritypolicy name

charts/aws-xray/Chart.yaml, charts/aws-xray/README.md, charts/aws-xray/values.yaml
Use official docker image instead of my custom image
Use latest (3.3.1) xray-daemon version
=> Update aws-xray-daemon version

charts/aws-xray/Chart.yaml, charts/aws-xray/README.md, charts/aws-xray/values.yaml
=> Bump xray-daemon version to 3.3.2

charts/aws-xray/Chart.yaml, charts/aws-xray/templates/daemonset.yaml
=> Official xray docker uses another binary path

charts/goldpinger/Chart.yaml, charts/goldpinger/README.md, charts/goldpinger/templates/daemonset.yaml, charts/goldpinger/values.yaml
Signed-off-by: Joost Coelingh <joost.coelingh@eu.equinix.com>
Add support for setting updateStrategy, in large clusters this takes long with the default (type: rollingUpdate, maxUnavailable: 1 at the time).
=> feat(goldpinger): add support to configure updateStrategy

charts/aws-xray/Chart.yaml, charts/aws-xray/README.md, charts/aws-xray/values.yaml
New version of aws-xray-daemon has been released
=> Bump aws-xray-daemon version to 3.3.3

charts/aws-xray/Chart.yaml, charts/aws-xray/templates/daemonset.yaml, charts/aws-xray/values.yaml
Allow service account token to be properly mounted by configuring pod security context at the DaemonSet or Container scope.
This is required to use this chart with AWS EKS IAM Roles for Service Accounts.
The example User ID is correct [`10001`] and is based on the upstream source: https://github.com/aws/aws-xray-daemon/blob/master/Dockerfile
This implementation is copy+paste from what gets provided by default with a `helm create ...`
=> [aws-xray] feat: add securityContext and podSecurityContext

charts/goldpinger/Chart.yaml, charts/goldpinger/values.yaml
My previous PR introduced wrongly formatted rule.
=> fix(goldpinger): fix default prometheusRule.

charts/goldpinger/Chart.yaml, charts/goldpinger/templates/_helpers.tpl, charts/goldpinger/templates/clusterrole.yaml, charts/goldpinger/templates/clusterrolebinding.yaml, charts/goldpinger/templates/daemonset.yaml, charts/goldpinger/templates/ingress.yaml, charts/goldpinger/templates/podsecuritypolicy.yaml, charts/goldpinger/templates/service.yaml, charts/goldpinger/templates/serviceaccount.yaml, charts/goldpinger/templates/servicemonitor.yaml, charts/goldpinger/values.yaml
Use actual Ingress api version
Template labels and selectors
Template labels, use latest ingress version
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #46 
=> feature: goldpinger update chart

charts/goldpinger/Chart.yaml, charts/goldpinger/README.md, charts/goldpinger/values.yaml
Bump up version image
latest version v3.3.0
=> [goldpinger] Update image tags for version v3.3.0 

charts/goldpinger/Chart.yaml, charts/goldpinger/README.md, charts/goldpinger/values.yaml
=> feat: bump goldpinger version

charts/aws-xray/Chart.yaml, charts/aws-xray/README.md, charts/aws-xray/values.yaml
=> feat: bump aws-xray version

.github/PULL_REQUEST_TEMPLATE.md, charts/aws-xray/Chart.yaml, charts/aws-xray/README.md, charts/aws-xray/templates/_helpers.tpl, charts/aws-xray/templates/configmap.yaml, charts/aws-xray/templates/daemonset.yaml, charts/aws-xray/templates/service.yaml, charts/aws-xray/values.yaml
Use new style labels and selectors
Use properly indentation
Remove extra documentation
Change pull request template
=> feat: rework aws-xray helm chart

charts/goldpinger/Chart.yaml
=> feat: bump goldpinger image

charts/goldpinger/Chart.yaml, charts/goldpinger/templates/daemonset.yaml
=> fix: wrong ds template indentation

charts/goldpinger/Chart.yaml, charts/goldpinger/templates/daemonset.yaml
=> fix: indentation in goldpinger DS

charts/goldpinger/Chart.yaml, charts/goldpinger/templates/daemonset.yaml, charts/goldpinger/values.yaml
For better security posture goldpinger deployment, we might need to specify security to run as non root etc.
NA
@okgolove
=> feat: goldpinger: option to specify security context

charts/goldpinger/Chart.yaml, charts/goldpinger/templates/configmap.yaml, charts/goldpinger/templates/daemonset.yaml, charts/goldpinger/values.yaml
Supports zap logger config as json file mounted under /config/zap.json
=> feat: support zap logger config

charts/aws-xray/Chart.yaml
=> feat: bump aws-xray to 3.3.6

charts/aws-xray/Chart.yaml, charts/aws-xray/templates/daemonset.yaml, charts/aws-xray/values.yaml
Optionally allows the setting of priorityClassName for the aws-xray pod
=> Allow specifying the priorityClassName for the pods

charts/goldpinger/Chart.yaml, charts/goldpinger/values.yaml
It does not make sense to have default service type loadbalancer
=> feat: change default servicetype

.github/workflows/lint_test.yaml
=> chore: user matrix

charts/goldpinger/Chart.yaml, charts/goldpinger/templates/daemonset.yaml
=> feat: remove extra line

charts/aws-xray/Chart.yaml
=> feat: bump aws-xray to 3.3.8

.github/workflows/lint_test.yaml
=> chore: bump kubernetes version using in tests

charts/goldpinger/Chart.yaml, charts/goldpinger/values.yaml
In 3.9.0 upstream rebased on a non-root container. Listening on port 80 is no longer possible.
This adjusts the default port to 8080 instead.
```
{"level":"fatal","ts":"2023-12-13T15:08:18.411Z","caller":"goldpinger/main.go:187","message":"Error serving the API","error":
"listen tcp 0.0.0.0:80: bind: permission denied"}
```
=> Update default Goldpinger port to 8080

charts/aws-xray/Chart.yaml
=> feat: bump aws-xray

charts/goldpinger/README.md
=> feat: deprecate goldpinger helm chart

charts/aws-xray/Chart.yaml
=> feat: bump aws xray version

charts/aws-xray/Chart.yaml
=> feat: bump aws-xray daemon version
